name: smart_pag_contract
description: apenas assinaturas de métodos para auxilio de deploy e testagem em FlutterFlow
version: 0.0.22
repository: https://github.com/fabricioJunior/pagSeguroSmartPos

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
